/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Fri Jul 12 22:44:43 2024 */

/* parameterized module instance */
lvdsClk __ (.CLKI( ), .CLKFB( ), .CLKOP( ));
